/**
 * Static lookup: region code → iNat place_id.
 *
 * Generated by scripts/build-inat-places.ts against the live iNat
 * /v1/places/autocomplete endpoint. Re-run if iNat ever renumbers.
 *
 * Last generated: 2026-05-27T03:01:12.600Z
 */

const US_STATES: Record<string, number> = {
  "US-AL": 19,
  "US-AK": 6,
  "US-AZ": 40,
  "US-AR": 36,
  "US-CA": 14,
  "US-CO": 34,
  "US-CT": 49,
  "US-DE": 4,
  "US-DC": 5,
  "US-FL": 21,
  "US-GA": 23,
  "US-HI": 11,
  "US-ID": 22,
  "US-IL": 35,
  "US-IN": 20,
  "US-IA": 24,
  "US-KS": 25,
  "US-KY": 26,
  "US-LA": 27,
  "US-ME": 17,
  "US-MD": 39,
  "US-MA": 2,
  "US-MI": 29,
  "US-MN": 38,
  "US-MS": 37,
  "US-MO": 28,
  "US-MT": 16,
  "US-NE": 3,
  "US-NV": 50,
  "US-NH": 41,
  "US-NJ": 51,
  "US-NM": 9,
  "US-NY": 48,
  "US-NC": 30,
  "US-ND": 13,
  "US-OH": 31,
  "US-OK": 12,
  "US-OR": 10,
  "US-PA": 42,
  "US-RI": 8,
  "US-SC": 43,
  "US-SD": 44,
  "US-TN": 45,
  "US-TX": 18,
  "US-UT": 52,
  "US-VT": 47,
  "US-VA": 7,
  "US-WA": 46,
  "US-WV": 33,
  "US-WI": 32,
  "US-WY": 15,
};

const CA_PROVINCES: Record<string, number> = {
  "CA-AB": 6834,
  "CA-BC": 7085,
  "CA-MB": 7590,
  "CA-NB": 7587,
  "CA-NL": 7289,
  "CA-NS": 6853,
  "CA-NT": 9079,
  "CA-NU": 13335,
  "CA-ON": 6883,
  "CA-PE": 9116,
  "CA-QC": 13336,
  "CA-SK": 7953,
  "CA-YT": 13337,
};

const ALL: Record<string, number> = { ...US_STATES, ...CA_PROVINCES };

/** Returns the iNat place_id for a region code, or null if unknown. */
export function inatPlaceIdFor(regionCode: string): number | null {
  return ALL[regionCode] ?? null;
}

/**
 * Returns the array of iNat place_ids for a set of region codes, dropping
 * any unknown codes. Used by the ingest worker to scope iNat queries.
 */
export function inatPlaceIdsFor(
  regionCodes: ReadonlyArray<string>,
): number[] {
  const out: number[] = [];
  for (const c of regionCodes) {
    const id = ALL[c];
    if (id != null) out.push(id);
  }
  return out;
}
