/**
 * Look up the correct iNat place_id for every US state + DC and every
 * Canadian province / territory, then write the corrected static map to
 * src/lib/sources/inat-places.ts.
 *
 * Run once: `pnpm tsx scripts/build-inat-places.ts`
 */

import { writeFileSync } from "node:fs";
import path from "node:path";

const OUT = path.resolve(
  __dirname,
  "..",
  "src",
  "lib",
  "sources",
  "inat-places.ts",
);

// USPS → state name + country code we'll match against `display_name`.
const US_STATES: Array<[string, string]> = [
  ["AL", "Alabama"], ["AK", "Alaska"], ["AZ", "Arizona"], ["AR", "Arkansas"],
  ["CA", "California"], ["CO", "Colorado"], ["CT", "Connecticut"], ["DE", "Delaware"],
  ["DC", "District of Columbia"], ["FL", "Florida"], ["GA", "Georgia"],
  ["HI", "Hawaii"], ["ID", "Idaho"], ["IL", "Illinois"], ["IN", "Indiana"],
  ["IA", "Iowa"], ["KS", "Kansas"], ["KY", "Kentucky"], ["LA", "Louisiana"],
  ["ME", "Maine"], ["MD", "Maryland"], ["MA", "Massachusetts"], ["MI", "Michigan"],
  ["MN", "Minnesota"], ["MS", "Mississippi"], ["MO", "Missouri"], ["MT", "Montana"],
  ["NE", "Nebraska"], ["NV", "Nevada"], ["NH", "New Hampshire"], ["NJ", "New Jersey"],
  ["NM", "New Mexico"], ["NY", "New York"], ["NC", "North Carolina"],
  ["ND", "North Dakota"], ["OH", "Ohio"], ["OK", "Oklahoma"], ["OR", "Oregon"],
  ["PA", "Pennsylvania"], ["RI", "Rhode Island"], ["SC", "South Carolina"],
  ["SD", "South Dakota"], ["TN", "Tennessee"], ["TX", "Texas"], ["UT", "Utah"],
  ["VT", "Vermont"], ["VA", "Virginia"], ["WA", "Washington"],
  ["WV", "West Virginia"], ["WI", "Wisconsin"], ["WY", "Wyoming"],
];

const CA_PROVINCES: Array<[string, string]> = [
  ["AB", "Alberta"], ["BC", "British Columbia"], ["MB", "Manitoba"],
  ["NB", "New Brunswick"], ["NL", "Newfoundland and Labrador"],
  ["NS", "Nova Scotia"], ["NT", "Northwest Territories"],
  ["NU", "Nunavut"], ["ON", "Ontario"], ["PE", "Prince Edward Island"],
  ["QC", "Quebec"], ["SK", "Saskatchewan"], ["YT", "Yukon"],
];

const BASE = "https://api.inaturalist.org/v1";
const UA = "insectid-checklist place-id builder (mailto:dev@example.org)";

interface PlaceResult {
  id: number;
  name: string;
  admin_level: number | null;
  display_name: string;
}

async function lookup(
  query: string,
  expectedCountryAbbr: string,
): Promise<{ id: number; name: string } | null> {
  // Polite rate limit (≤2 req/s).
  await new Promise((r) => setTimeout(r, 600));
  const url = `${BASE}/places/autocomplete?${new URLSearchParams({
    q: query,
    per_page: "20",
  })}`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) {
    console.error(`  ! ${query}: HTTP ${res.status}`);
    return null;
  }
  const json = (await res.json()) as { results: PlaceResult[] };

  // admin_level=10 means top-level subdivision (state / province / etc.).
  // The display name carries country at the end, e.g. "Indiana, US".
  for (const r of json.results) {
    if (r.admin_level !== 10) continue;
    if (
      r.display_name.endsWith(`, ${expectedCountryAbbr}`) ||
      r.display_name === `${query}, ${expectedCountryAbbr}`
    ) {
      return { id: r.id, name: r.name };
    }
  }
  // Fallback: first admin_level=10 result if no country-suffix match.
  const al10 = json.results.find((r) => r.admin_level === 10);
  if (al10) return { id: al10.id, name: al10.name };
  return null;
}

async function main() {
  const out: Record<string, number> = {};

  console.log("[build-inat-places] US states (51)…");
  for (const [usps, name] of US_STATES) {
    const r = await lookup(name, "US");
    if (!r) {
      console.error(`  ! no place_id for US-${usps} (${name})`);
      continue;
    }
    out[`US-${usps}`] = r.id;
    console.log(`  US-${usps} → ${r.id} (${r.name})`);
  }

  console.log("[build-inat-places] Canadian provinces (13)…");
  for (const [abbr, name] of CA_PROVINCES) {
    const r = await lookup(name, "CA");
    if (!r) {
      console.error(`  ! no place_id for CA-${abbr} (${name})`);
      continue;
    }
    out[`CA-${abbr}`] = r.id;
    console.log(`  CA-${abbr} → ${r.id} (${r.name})`);
  }

  // Render the TS module.
  const usEntries = US_STATES.map(([usps]) => `  "US-${usps}": ${out[`US-${usps}`] ?? "/* missing */"},`).join("\n");
  const caEntries = CA_PROVINCES.map(([abbr]) => `  "CA-${abbr}": ${out[`CA-${abbr}`] ?? "/* missing */"},`).join("\n");

  const ts = `/**
 * Static lookup: region code → iNat place_id.
 *
 * Generated by scripts/build-inat-places.ts against the live iNat
 * /v1/places/autocomplete endpoint. Re-run if iNat ever renumbers.
 *
 * Last generated: ${new Date().toISOString()}
 */

const US_STATES: Record<string, number> = {
${usEntries}
};

const CA_PROVINCES: Record<string, number> = {
${caEntries}
};

const ALL: Record<string, number> = { ...US_STATES, ...CA_PROVINCES };

/** Returns the iNat place_id for a region code, or null if unknown. */
export function inatPlaceIdFor(regionCode: string): number | null {
  return ALL[regionCode] ?? null;
}

/**
 * Returns the array of iNat place_ids for a set of region codes, dropping
 * any unknown codes. Used by the ingest worker to scope iNat queries.
 */
export function inatPlaceIdsFor(
  regionCodes: ReadonlyArray<string>,
): number[] {
  const out: number[] = [];
  for (const c of regionCodes) {
    const id = ALL[c];
    if (id != null) out.push(id);
  }
  return out;
}
`;
  writeFileSync(OUT, ts);
  console.log(`[build-inat-places] wrote ${OUT}`);
}

main().catch((err) => {
  console.error("[build-inat-places] failed:", err);
  process.exit(1);
});
