/**
 * Region name helpers. Wraps the autogenerated registry with friendly
 * accessors used throughout the UI.
 *
 * Identifier shapes:
 *   - US county FIPS: 5-digit string (e.g. "18001")
 *   - US state FIPS:  2-digit string (e.g. "18")
 *   - US state code:  "US-IN"
 *   - CA province code: "CA-ON"
 *
 * Note: `records.countyFips` holds *either* a US county FIPS or a CA
 * province code, since CA census divisions are out of scope (province is
 * the smallest Canadian region atom). Helpers handle both.
 *
 * Functions return `null` for unknown ids; callers fall back to the raw id
 * (so a future-added county still surfaces something, just unprettified).
 */

import {
  CA_PROVINCES,
  US_COUNTIES,
  US_STATES_BY_CODE,
  US_STATES_BY_FIPS,
} from "./regions.generated";

export function countyName(fips: string | null | undefined): string | null {
  if (!fips) return null;
  if (US_COUNTIES[fips]) return US_COUNTIES[fips].name;
  if (CA_PROVINCES[fips]) return CA_PROVINCES[fips].name;
  return null;
}

export function countyLabel(fips: string | null | undefined): string | null {
  if (!fips) return null;
  const c = US_COUNTIES[fips];
  if (c) return `${c.name} County, ${c.stateCode.slice(3)}`;
  const p = CA_PROVINCES[fips];
  if (p) return `${p.name}, ${fips.slice(3)}`;
  return null;
}

export function stateNameByFips(fips: string | null | undefined): string | null {
  if (!fips) return null;
  return US_STATES_BY_FIPS[fips]?.name ?? null;
}

export function stateName(code: string | null | undefined): string | null {
  if (!code) return null;
  return (
    US_STATES_BY_CODE[code]?.name ??
    CA_PROVINCES[code]?.name ??
    null
  );
}

/**
 * Region descriptor lookup — works for US-IN, CA-ON, etc. Returns the
 * jurisdiction name + scope ("state" | "province") if known.
 */
export function regionDescriptor(
  code: string | null | undefined,
): { name: string; scope: "state" | "province" } | null {
  if (!code) return null;
  if (US_STATES_BY_CODE[code])
    return { name: US_STATES_BY_CODE[code].name, scope: "state" };
  if (CA_PROVINCES[code])
    return { name: CA_PROVINCES[code].name, scope: "province" };
  return null;
}

export { CA_PROVINCES, US_COUNTIES, US_STATES_BY_CODE, US_STATES_BY_FIPS };
